<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniCore.Domain\OmniCore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\AlcatelRadioLastMiles\Commands\" />
    <Folder Include="Features\BTS\Commands\" />
    <Folder Include="Features\CeragonRadioLastMiles\Commands\" />
    <Folder Include="Features\ClientCategories\Commands\" />
    <Folder Include="Features\Clients\Commands\" />
    <Folder Include="Features\Clients\Queries\" />
    <Folder Include="Features\FiberLastMiles\Commands\" />
    <Folder Include="Features\FiberLastMiles\Queries\" />
    <Folder Include="Features\InternetServices\Commands\" />
    <Folder Include="Features\InternetServices\Queries\" />
    <Folder Include="Features\IPPoPs\Commands\" />
    <Folder Include="Features\IPPoPs\Queries\" />
    <Folder Include="Features\LeasedLineServices\Commands\" />
    <Folder Include="Features\LeasedLineServices\Queries\" />
    <Folder Include="Features\Links\Commands\" />
    <Folder Include="Features\Links\Queries\" />
    <Folder Include="Features\NeraRadioLastMiles\Commands\" />
    <Folder Include="Features\NeraRadioLastMiles\Queries\" />
    <Folder Include="Features\PettyCashVouchers\Commands\" />
    <Folder Include="Features\PettyCashVouchers\Queries\" />
    <Folder Include="Features\PRIServices\Commands\" />
    <Folder Include="Features\PRIServices\Queries\" />
    <Folder Include="Features\Routers\Commands\" />
    <Folder Include="Features\Routers\Queries\" />
    <Folder Include="Features\Servers\Commands\" />
    <Folder Include="Features\Servers\Queries\" />
    <Folder Include="Features\SIPServices\Commands\" />
    <Folder Include="Features\SIPServices\Queries\" />
    <Folder Include="Features\States\Commands\" />
    <Folder Include="Features\States\Queries\" />
    <Folder Include="Features\Switches\Commands\" />
    <Folder Include="Features\Switches\Queries\" />
    <Folder Include="Features\TechnicalRegions\Commands\" />
    <Folder Include="Features\TechnicalRegions\Queries\" />
    <Folder Include="Features\Tickets\Commands\" />
    <Folder Include="Features\Units\Commands\" />
    <Folder Include="Features\Units\Queries\" />
    <Folder Include="Features\UserCategoriess\Commands\" />
    <Folder Include="Features\UserCategoriess\Queries\" />
    <Folder Include="Features\Zones\Commands\" />
    <Folder Include="Features\Zones\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
